In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences

sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size = 10000

In [5]:
#one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]

In [6]:
one_hot_repr

[[2922, 2672, 6725, 3565],
 [2922, 2672, 6725, 6555],
 [2922, 2298, 6725, 4995],
 [4845, 2226, 8037, 5409, 924],
 [4845, 2226, 8037, 5409, 3766],
 [4189, 2922, 9356, 6725, 2389],
 [5205, 5616, 928, 5409]]

In [7]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 2922, 2672, 6725, 3565],
       [   0,    0,    0,    0, 2922, 2672, 6725, 6555],
       [   0,    0,    0,    0, 2922, 2298, 6725, 4995],
       [   0,    0,    0, 4845, 2226, 8037, 5409,  924],
       [   0,    0,    0, 4845, 2226, 8037, 5409, 3766],
       [   0,    0,    0, 4189, 2922, 9356, 6725, 2389],
       [   0,    0,    0,    0, 5205, 5616,  928, 5409]])

In [12]:
#feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 190ms/step


array([[[-0.02503159,  0.01380679, -0.04132991,  0.04589561,
          0.04310694,  0.02433944, -0.01789293,  0.03311587,
         -0.02292454, -0.03727478],
        [-0.02503159,  0.01380679, -0.04132991,  0.04589561,
          0.04310694,  0.02433944, -0.01789293,  0.03311587,
         -0.02292454, -0.03727478],
        [-0.02503159,  0.01380679, -0.04132991,  0.04589561,
          0.04310694,  0.02433944, -0.01789293,  0.03311587,
         -0.02292454, -0.03727478],
        [-0.02503159,  0.01380679, -0.04132991,  0.04589561,
          0.04310694,  0.02433944, -0.01789293,  0.03311587,
         -0.02292454, -0.03727478],
        [ 0.00036047, -0.02989846,  0.02885096,  0.02743177,
         -0.00210812,  0.03192655, -0.00743289, -0.04483407,
          0.03558121, -0.03463963],
        [-0.00118529, -0.01279131, -0.00618459,  0.04474196,
          0.00020465, -0.04695308, -0.03580192, -0.0233769 ,
         -0.01856933,  0.03145139],
        [-0.04028051,  0.00775919, -0.00918659, -0.0

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 62ms/step


array([[-0.02503159,  0.01380679, -0.04132991,  0.04589561,  0.04310694,
         0.02433944, -0.01789293,  0.03311587, -0.02292454, -0.03727478],
       [-0.02503159,  0.01380679, -0.04132991,  0.04589561,  0.04310694,
         0.02433944, -0.01789293,  0.03311587, -0.02292454, -0.03727478],
       [-0.02503159,  0.01380679, -0.04132991,  0.04589561,  0.04310694,
         0.02433944, -0.01789293,  0.03311587, -0.02292454, -0.03727478],
       [-0.02503159,  0.01380679, -0.04132991,  0.04589561,  0.04310694,
         0.02433944, -0.01789293,  0.03311587, -0.02292454, -0.03727478],
       [ 0.00036047, -0.02989846,  0.02885096,  0.02743177, -0.00210812,
         0.03192655, -0.00743289, -0.04483407,  0.03558121, -0.03463963],
       [-0.00118529, -0.01279131, -0.00618459,  0.04474196,  0.00020465,
        -0.04695308, -0.03580192, -0.0233769 , -0.01856933,  0.03145139],
       [-0.04028051,  0.00775919, -0.00918659, -0.01024643,  0.03941934,
        -0.00734665, -0.04347867, -0.04001722